name: smart_ocr
description: "Flutter paketi olarak geliştirilmiş, OCR ve AI düzeltme özelliklerine sahip akıllı metin tanıma modülü."
version: 0.0.1
homepage: https://github.com/yourusername/smart_ocr

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # OCR
  google_mlkit_text_recognition: ^0.11.0
  
  # Image Handling
  image_picker: ^0.8.9
  
  # Responsive Design
  flutter_screenutil: ^5.9.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # Network
  http: ^1.2.0
  
  # AI Integration
  openai_dart: ^0.1.7

  # Permissions
  permission_handler: ^11.3.0
  
  # Utils
  logger: ^2.0.2+1
  intl: ^0.19.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  very_good_analysis: ^5.1.0
  
  # Code Generation
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  drift_dev: ^2.16.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
